### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/comloadgo#15]
We have here some white space

**URL tested:** https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fpreview.hs-sites.com%2F_hcms%2Fpreview%2Ftemplate%2Fmulti%3Fis_buffered_template_layout%3Dtrue%26portalId%3D4633697%26tc_deviceCategory%3Dundefined%26template_layout_id%3D6553830069%26updated%3D1542643908819&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XS |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d9a624d0aaacddda4efc998afb73632662745ca8/realios_iPhone_XS.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/d9a624d0aaacddda4efc998afb73632662745ca8/realios_iPhone_XS.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fpreview.hs-sites.com%2F_hcms%2Fpreview%2Ftemplate%2Fmulti%3Fis_buffered_template_layout%3Dtrue%26portalId%3D4633697%26tc_deviceCategory%3Dundefined%26template_layout_id%3D6553830069%26updated%3D1542643908819&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48777856-88bc8900-ecf5-11e8-8e76-9562bb2b136d.png)
done
