### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/comloadgo#16]
We don't have social icons for any device here

**URL tested:** https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fpreview.hs-sites.com%2F_hcms%2Fpreview%2Ftemplate%2Fmulti%3Fis_buffered_template_layout%3Dtrue%26portalId%3D4633697%26tc_deviceCategory%3Dundefined%26template_layout_id%3D6553830069%26updated%3D1542643908819&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 11.1 |
| Operating System | OS X High Sierra |
| Resolution | 1600x768 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/73114b9a2ffd8d75f1614d8c0b410bbbe121da6b/machs_safari_11.1.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/73114b9a2ffd8d75f1614d8c0b410bbbe121da6b/machs_safari_11.1.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=High+Sierra&browser=Safari&browser_version=11.1&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fpreview.hs-sites.com%2F_hcms%2Fpreview%2Ftemplate%2Fmulti%3Fis_buffered_template_layout%3Dtrue%26portalId%3D4633697%26tc_deviceCategory%3Dundefined%26template_layout_id%3D6553830069%26updated%3D1542643908819&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://preview.hs-sites.com/_hcms/preview/template/multi?is_buffered_template_layout=true&portalId=4633697&tc_deviceCategory=undefined&template_layout_id=6553830069&updated=1542643908819) to reproduce the issue on Browserstack:**

**Comment by socialjutt** [comment]
![image](https://user-images.githubusercontent.com/4739198/48777658-059b3300-ecf5-11e8-9c64-ca98dc28ab0c.png)
fixed
